before:
  hooks:
builds:
  - env:
    - CGO_ENABLED=0
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - README.md
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
brew:
  github:
    owner: gojek
    name: homebrew-tap
  commit_author:
    name: "Karan Misra"
    email: "karan.misra@go-jek.com"
  folder: Formula
  homepage: "https://github.com/gojek/xp"
  description: "extreme programming made simple"
